nosana:
    description: Effect Network

global:
    image: registry.hub.docker.com/library/node:18
    trigger:
        branch:
            - master
jobs:
    - name: compile
      image: registry.hub.docker.com/jeisses/eos-cdt-make:latest
      commands:
        - make all
    - name: install
      commands:
          - npm ci
          - npm run lumo e2e.macros
      artifacts:  
          - name: node_modules
            path: ./node_modules/